### PR TITLE
fix: catch exception on polling

### LINKED ISSUE #45: Background polling throws "System.SystemException: Unable to fetch flag configurationFlag configuration not present in response"
We recently deployed a mobile app that used the Eppo client in server mode, in order to enable automatic hourly polling for new flag configurations:

```dotnet
var eppoClientConfig = new EppoClientConfig (_apiKey, new AssignmentLogger ()) {
	PollingIntervalInMillis = (long)TimeSpan.FromHours (1).TotalMilliseconds,
	PollingJitterInMillis = 0
};

_client = EppoClient.Init (eppoClientConfig);
```

Unfortunately, we saw a small number of app crashes appearing in our logs after this change, with the following stack trace: 

```
System.SystemException: Unable to fetch flag configurationFlag configuration not present in response
  ?, in VersionedResourceResponse<FlagConfigurationResponse> ConfigurationRequester.FetchFlags(string lastConfigVersion)
  ?, in void ConfigurationRequester.LoadConfiguration()
  ?, in void FetchExperimentsTask.Run()
  ?, in void FetchExperimentsTask.<.ctor>b__4_0(?)+(object state) => { }
  ?, in void TimerQueueTimer.s_callCallbackInContext(object state)
  ?, in void TimerQueueTimer.CallCallback(bool)
  ?, in void TimerQueueTimer.Fire(bool)
  ?, in void TimerQueueTimer.System.Threading.IThreadPoolWorkItem.Execute()
  ?, in void ThreadPoolWorkQueue.DispatchItemWithAutoreleasePool(object, Thread)
  ?, in bool ThreadPoolWorkQueue.Dispatch()
  ?, in void WorkerThread.WorkerThreadStart()
  ?, in void Thread.StartCallback()
```

As far as I could tell, this exception can occur whenever the API call to get the new configuration receives a response with no content body and a HTTP response code other than `HttpStatusCode.NotModified` [(link)](https://github.com/Eppo-exp/dot-net-server-sdk/blob/main/dot-net-sdk/http/ConfigurationRequester.cs#L113). I would therefore assume that this happens whenever some kind of error occurs in the API call.

Because this is happening on background worker threads, running this in a mobile app means that the unhandled errors can cause the entire app to crash, as we do not have a way to catch these errors properly. Would it be possible to either add error handling that catches these exceptions, or add some hook for SDK users to attach their own error handlers?

### PR DESCRIPTION
**Pull request by typotter**
Eppo internal: fixes FF-3378
fixes #45

### CODE REVIEW

**Review by leoromanovsky — APPROVED** [review]

File: dot-net-sdk/tasks/FetchExperimentsTask.cs [hunk 1]
```diff
@@ -36,7 +40,14 @@ internal void Run()
         var nextTick = TimeIntervalInMillis - jitter;
 
         Timer.Change(nextTick, Timeout.Infinite);
-        ConfigLoader.LoadConfiguration();
+        try
+        {
+            ConfigLoader.LoadConfiguration();
+        }
+        catch (Exception e)
```
Comment (aarsilv) [inline dot-net-sdk/tasks/FetchExperimentsTask.cs:47]: 👍

**Review by aarsilv — APPROVED** [review]
👍
